apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: prod-stack
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
