---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod-stack
type: Opaque
data:
  password: ZGVtbzEyMzQ1Ng==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: prod-stack
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
