---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: chaas-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/shivaswaroop40/chaas-gitops
  ref:
    branch: main
